name: macOS/Ubuntu compile check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  ubuntu_compile_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: minishell
      run:  make

  macos_compile_check:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: minishell
      run:  make
